Repository cartesi/rollups-explorer, pull requests merged in 2024-03, with the labels that each got.

#96 #72 Add ERC-721 Deposit form
  apps/web/src/components/sendTransaction.tsx
  apps/web/test/components/sendTransaction.test.tsx
  packages/ui/src/ERC20DepositForm.tsx
  packages/ui/src/ERC721DepositForm.tsx
  packages/ui/src/EtherDepositForm.tsx
  packages/ui/src/index.tsx
  packages/ui/test/ERC20DepositForm.test.tsx
  packages/ui/test/ERC721DepositForm.test.tsx
Labels: Type: Feature

#138 #127 Add unit tests for transaction forms
  packages/ui/src/ERC721DepositForm.tsx
  packages/ui/src/hooks/useTokensOfOwnerByIndex.ts
  packages/ui/test/ERC20DepositForm.test.tsx
  packages/ui/test/ERC721DepositForm.test.tsx
  packages/ui/test/EtherDepositForm.test.tsx
  packages/ui/test/RawInputForm.test.tsx
  packages/ui/test/hooks/useTokensOfOwnerByIndex.test.ts
Labels: Type: Enhancement

#139 Fix Page Input No Result Display and Query Missing on Refresh
  apps/web/src/components/applications/applicationsTable.tsx
  apps/web/src/components/inputs/inputs.tsx
  apps/web/src/components/inputs/inputsTable.tsx
  apps/web/src/components/latestEntriesTable.tsx
  apps/web/src/components/search.tsx
  apps/web/src/providers/theme.tsx
  apps/web/test/components/latestEntriesTable.test.tsx
  apps/web/test/components/search.test.tsx
Labels: Type: Bug
